services:
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: recipeswiper
      MARIADB_USER: recipeuser
      MARIADB_PASSWORD: recipe1234
    volumes:
      - db_data:/var/lib/mysql
      - ./recipeswiper-database:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    image: ghcr.io/janishuber/recipeswiper-backend:latest
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: recipeswiper
      DB_USER: recipeuser
      DB_PASSWORD: recipe123
    ports:
      - "9080:9080"
    depends_on:
      - db

  frontend:
    image: ghcr.io/janishuber/recipeswiper-frontend:latest
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data: