POST http://localhost:9090/api/recipeswiper/new/recipe
Content-Type: application/json

###

POST http://localhost:9090/api/recipeswiper/new/group
Content-Type: application/json

###

POST http://localhost:9090/api/recipeswiper/new/user
Content-Type: application/json

{
  "username": "Janis"
}

###

POST http://localhost:9090/api/recipeswiper/join
Content-Type: application/json

{
  "groupToken": "3247f304-b9c7-4e3d-b518-c2c9ed07238f",
  "userToken": "e8965b5b-b572-4873-af10-bf1dd6e18619"
}

###

GET http://localhost:9090/api/recipeswiper/cb70bd38-545d-458f-878f-55b38f8ede6b/load/recipes
Content-Type: application/json

###

GET http://localhost:9090/api/recipeswiper/3247f304-b9c7-4e3d-b518-c2c9ed07238f/get/recipes
Content-Type: application/json

###

POST http://localhost:9090/api/recipeswiper/3247f304-b9c7-4e3d-b518-c2c9ed07238f/like
Content-Type: application/json

{
  "recipeId": 1
}

###

GET http://localhost:9090/api/recipeswiper/groups/2eab7c13-8afc-4cf6-9290-9864e2848b4e/get/results
Content-Type: application/json

###

POST http://127.0.0.1:9080/api/recipeswiper/new/user
Content-Type: application/json

{
  "username": "Janis"
}