services:
  - type: web
    name: recipeswiper-backend
    env: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .

    # Environment variables
    envVars:
      - key: DATABASE_URL
        value: jdbc:mariadb://recipeswiper-db:3306/recipeswiper
      - key: DB_USER
        value: appuser
      - key: DB_PASSWORD
        value: apppass
      - key: JAVA_OPTS
        value: "-Xmx256m -Xms128m -XX:+UseContainerSupport"

    # Health check
    healthCheckPath: /api/recipeswiper/health

    # Auto-deploy from main branch
    autoDeploy: true
