name: Create and publish Docker Compose images

on:
  push:
    branches: [ 'main' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: janishuber/recipeswiper

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build WAR file
        run: mvn clean package --file recipeswiper-backend/pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push all images
        id: bake
        uses: docker/bake-action@v4
        with:
          files: docker-compose.yml
          push: true
          set: |
            backend.tags=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-backend:latest
            frontend.tags=${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-frontend:latest

      - name: Attest backend image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-backend
          subject-digest: ${{ steps.bake.outputs.backend.digest }}
          push-to-registry: tr
      - name: Attest frontend image
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-frontend
          subject-digest: ${{ steps.bake.outputs.frontend.digest }}
          push-to-registry: true